name: deploy to aliyun

on:
  push:
    branches: ['main']

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@master
      - name: 安装 pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true
      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      # npm install and build
      - name: 安装依赖
        run: pnpm install --frozen-lockfile
        env:
          CI: true
      - name: 构建导航
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: pnpm run build
      - name: 部署到阿里服务器
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ALIYUN_SERVER_ACCESS_TOKEN }}
          ARGS: "-avz --delete"
          SOURCE: "dist/browser/"
          REMOTE_HOST: ${{ secrets.ALIYUN_SERVER_HOST }}
          REMOTE_USER: root
          TARGET: /home/admin/deploy/cosarty-nav/
